// Code generated by scapi/gen. DO NOT EDIT.
package contractsapi

import (
	"github.com/0xPolygon/polygon-edge/types"
)

type InitializeApexBridgeContractsBridgeFn struct {
	Owner        types.Address `abi:"_owner"`
	UpgradeAdmin types.Address `abi:"_upgradeAdmin"`
}

func (i *InitializeApexBridgeContractsBridgeFn) Sig() []byte {
	return ApexBridgeContracts.Bridge.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsBridgeFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Bridge.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsBridgeFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Bridge.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsBridgeFn struct {
	ClaimsAddress        types.Address `abi:"_claimsAddress"`
	SignedBatchesAddress types.Address `abi:"_signedBatchesAddress"`
	SlotsAddress         types.Address `abi:"_slotsAddress"`
	ValidatorsAddress    types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesApexBridgeContractsBridgeFn) Sig() []byte {
	return ApexBridgeContracts.Bridge.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsBridgeFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Bridge.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsBridgeFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Bridge.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsClaimsHelperFn struct {
	Owner        types.Address `abi:"_owner"`
	UpgradeAdmin types.Address `abi:"_upgradeAdmin"`
}

func (i *InitializeApexBridgeContractsClaimsHelperFn) Sig() []byte {
	return ApexBridgeContracts.ClaimsHelper.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsClaimsHelperFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.ClaimsHelper.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsClaimsHelperFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.ClaimsHelper.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsClaimsHelperFn struct {
	ClaimsAddress        types.Address `abi:"_claimsAddress"`
	SignedBatchesAddress types.Address `abi:"_signedBatchesAddress"`
}

func (s *SetDependenciesApexBridgeContractsClaimsHelperFn) Sig() []byte {
	return ApexBridgeContracts.ClaimsHelper.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsClaimsHelperFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.ClaimsHelper.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsClaimsHelperFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.ClaimsHelper.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsClaimsFn struct {
	Owner                   types.Address `abi:"_owner"`
	UpgradeAdmin            types.Address `abi:"_upgradeAdmin"`
	MaxNumberOfTransactions uint16        `abi:"_maxNumberOfTransactions"`
	TimeoutBlocksNumber     uint8         `abi:"_timeoutBlocksNumber"`
}

func (i *InitializeApexBridgeContractsClaimsFn) Sig() []byte {
	return ApexBridgeContracts.Claims.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsClaimsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Claims.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsClaimsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Claims.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsClaimsFn struct {
	BridgeAddress        types.Address `abi:"_bridgeAddress"`
	ClaimsHelperAddress  types.Address `abi:"_claimsHelperAddress"`
	ValidatorsAddress    types.Address `abi:"_validatorsAddress"`
	AdminContractAddress types.Address `abi:"_adminContractAddress"`
}

func (s *SetDependenciesApexBridgeContractsClaimsFn) Sig() []byte {
	return ApexBridgeContracts.Claims.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsClaimsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Claims.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsClaimsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Claims.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsSignedBatchesFn struct {
	Owner        types.Address `abi:"_owner"`
	UpgradeAdmin types.Address `abi:"_upgradeAdmin"`
}

func (i *InitializeApexBridgeContractsSignedBatchesFn) Sig() []byte {
	return ApexBridgeContracts.SignedBatches.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsSignedBatchesFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.SignedBatches.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsSignedBatchesFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.SignedBatches.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsSignedBatchesFn struct {
	BridgeAddress       types.Address `abi:"_bridgeAddress"`
	ClaimsHelperAddress types.Address `abi:"_claimsHelperAddress"`
	ValidatorsAddress   types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesApexBridgeContractsSignedBatchesFn) Sig() []byte {
	return ApexBridgeContracts.SignedBatches.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsSignedBatchesFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.SignedBatches.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsSignedBatchesFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.SignedBatches.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsSlotsFn struct {
	Owner        types.Address `abi:"_owner"`
	UpgradeAdmin types.Address `abi:"_upgradeAdmin"`
}

func (i *InitializeApexBridgeContractsSlotsFn) Sig() []byte {
	return ApexBridgeContracts.Slots.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsSlotsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Slots.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsSlotsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Slots.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsSlotsFn struct {
	BridgeAddress     types.Address `abi:"_bridgeAddress"`
	ValidatorsAddress types.Address `abi:"_validatorsAddress"`
}

func (s *SetDependenciesApexBridgeContractsSlotsFn) Sig() []byte {
	return ApexBridgeContracts.Slots.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsSlotsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Slots.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsSlotsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Slots.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsValidatorsFn struct {
	Owner        types.Address   `abi:"_owner"`
	UpgradeAdmin types.Address   `abi:"_upgradeAdmin"`
	Validators   []types.Address `abi:"_validators"`
}

func (i *InitializeApexBridgeContractsValidatorsFn) Sig() []byte {
	return ApexBridgeContracts.Validators.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsValidatorsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Validators.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsValidatorsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Validators.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsValidatorsFn struct {
	BridgeAddress types.Address `abi:"_bridgeAddress"`
}

func (s *SetDependenciesApexBridgeContractsValidatorsFn) Sig() []byte {
	return ApexBridgeContracts.Validators.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsValidatorsFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Validators.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsValidatorsFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Validators.Abi.Methods["setDependencies"], buf, s)
}

type InitializeApexBridgeContractsAdminFn struct {
	Owner        types.Address `abi:"_owner"`
	UpgradeAdmin types.Address `abi:"_upgradeAdmin"`
}

func (i *InitializeApexBridgeContractsAdminFn) Sig() []byte {
	return ApexBridgeContracts.Admin.Abi.Methods["initialize"].ID()
}

func (i *InitializeApexBridgeContractsAdminFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Admin.Abi.Methods["initialize"].Encode(i)
}

func (i *InitializeApexBridgeContractsAdminFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Admin.Abi.Methods["initialize"], buf, i)
}

type SetDependenciesApexBridgeContractsAdminFn struct {
	ClaimsAddress types.Address `abi:"_claimsAddress"`
}

func (s *SetDependenciesApexBridgeContractsAdminFn) Sig() []byte {
	return ApexBridgeContracts.Admin.Abi.Methods["setDependencies"].ID()
}

func (s *SetDependenciesApexBridgeContractsAdminFn) EncodeAbi() ([]byte, error) {
	return ApexBridgeContracts.Admin.Abi.Methods["setDependencies"].Encode(s)
}

func (s *SetDependenciesApexBridgeContractsAdminFn) DecodeAbi(buf []byte) error {
	return decodeMethod(ApexBridgeContracts.Admin.Abi.Methods["setDependencies"], buf, s)
}
