---
name: ApexBridge Testnet
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      e2e_apex_testnet_test:
        description: E2E ApexBridge Testnet Test
        type: boolean
        default: true
      e2e_apex_testnet_fund:
        description: E2E ApexBridge Testnet Fund
        type: boolean
        default: false
      e2e_apex_testnet_balances:
        description: E2E ApexBridge Testnet Balances
        type: boolean
        default: true

jobs:
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      e2e_apex_testnet_test: ${{ steps.test_input_check.outputs.e2e_apex_testnet_test }}
      e2e_apex_testnet_fund: ${{ steps.fund_input_check.outputs.e2e_apex_testnet_fund }}
      e2e_apex_testnet_balances: ${{ steps.balances_input_check.outputs.e2e_apex_testnet_balances }}
    steps:
      - name: Test Input Check
        id: test_input_check
        run: |
          if [[ "${{ inputs.e2e_apex_testnet_test }}" != "false" ]]; then
            echo "e2e_apex_testnet_test=true" >> $GITHUB_OUTPUT
          else
            echo "e2e_apex_testnet_test=false" >> $GITHUB_OUTPUT
          fi
      - name: Fund Input Check
        id: fund_input_check
        run: |
          if [[ "${{ inputs.e2e_apex_testnet_fund }}" != "false" ]]; then
            echo "e2e_apex_testnet_fund=true" >> $GITHUB_OUTPUT
          else
            echo "e2e_apex_testnet_fund=false" >> $GITHUB_OUTPUT
          fi
      - name: Balances Input Check
        id: balances_input_check
        run: |
          if [[ "${{ inputs.e2e_apex_testnet_balances }}" != "false" ]]; then
            echo "e2e_apex_testnet_balances=true" >> $GITHUB_OUTPUT
          else
            echo "e2e_apex_testnet_balances=false" >> $GITHUB_OUTPUT
          fi
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: build_blade
  e2e_apex_testnet_test:
    name: E2E ApexBridge Testnet Tests
    uses: ./.github/workflows/e2e-testnet-test.yml
    needs: [inputs_check, build_blade]
    with:
      e2e_apex_testnet_test: ${{ needs.inputs_check.outputs.e2e_apex_testnet_test }}
      e2e_apex_testnet_fund: ${{ needs.inputs_check.outputs.e2e_apex_testnet_fund }}
      e2e_apex_testnet_balances: ${{ needs.inputs_check.outputs.e2e_apex_testnet_balances }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      TESTNET_BRIDGING_API_KEY: ${{ secrets.TESTNET_BRIDGING_API_KEY }}
      E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.E2E_TESTNET_WALLET_KEYS_CONTENT }}
  notification_apex_testnet:
    name: ApexBridge Testnet Notification
    uses: ./.github/workflows/apex-notification-testnet.yml
    needs: [build_blade, lint, e2e_apex_testnet_test]
    if: success() || failure()
    with:
      environment: testnet
      build_blade_output: ${{ needs.build_blade.outputs.workflow_output }}
      lint_output: ${{ needs.lint.outputs.workflow_output }}
      e2e_apex_testnet_test_output: ${{ needs.e2e_apex_testnet_test.outputs.workflow_output }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
