---
name: ApexBridge CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
    inputs:
      lint:
        description: Lint
        type: boolean
        default: true
      unit_test:
        description: Unit Tests
        type: boolean
        default: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        default: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        default: true
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: boolean
        default: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: boolean
        default: true
      apex_bridge_ref:
        description: The branch/commit from the Apex Bridge
        type: string
        default: main
  workflow_call:
    inputs:
      lint:
        description: Lint
        type: boolean
        required: true
      unit_test:
        description: Unit Tests
        type: boolean
        required: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        required: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        required: true
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: string
        required: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: string
        required: true
      apex_bridge_ref:
        description: The branch/commit from the Apex Bridge
        type: string
        required: true
    outputs:
      build_blade:
        description: Build Blade output
        value: ${{ jobs.build_blade.outputs.workflow_output }}
      lint:
        description: Lint output
        value: ${{ jobs.lint.outputs.workflow_output }}
      unit_test:
        description: Unit Tests output
        value: ${{ jobs.unit_test.outputs.workflow_output }}
      e2e_polybft_test:
        description: E2E PolyBFT Tests output
        value: ${{ jobs.e2e_polybft_test.outputs.workflow_output }}
      e2e_apex_test:
        description: E2E ApexBridge Tests output
        value: ${{ jobs.e2e_apex_test.outputs.workflow_output }}
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: build_blade
    if: |
      inputs.lint || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  unit_test:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml
    needs: build_blade
    if: |
      inputs.unit_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      skip_redundant_tests: ${{ steps.redudant_test_input_check.outputs.skip_redundant_tests }}
      apex_bridge_ref: ${{ steps.apex_bridge_ref_input_check.outputs.apex_bridge_ref }}
    steps:
      - name: Redundant Tests Input Check
        id: redudant_test_input_check
        run: |
          if [[ "${{ inputs.e2e_apex_skip_redundant_tests }}" != "false" ]]; then
            echo "skip_redundant_tests=true" >> $GITHUB_OUTPUT
          else
            echo "skip_redundant_tests=false" >> $GITHUB_OUTPUT
          fi
      - name: Apex Bridge Ref Input Check
        id: apex_bridge_ref_input_check
        run: |
          if [[ "${{ inputs.apex_bridge_ref }}" == "" ]]; then
            echo "apex_bridge_ref=main" >> $GITHUB_OUTPUT
          else
            echo "apex_bridge_ref=${{ inputs.apex_bridge_ref }}" >> $GITHUB_OUTPUT
          fi
  e2e_polybft_test:
    name: E2E PolyBFT Tests
    uses: ./.github/workflows/e2e-polybft-test.yml
    needs: [build_blade, inputs_check]
    if: |
      inputs.e2e_polybft_test || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test:
    name: E2E ApexBridge Tests
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: [build_blade, inputs_check]
    if: |
      inputs.e2e_apex_test || 
      github.event_name == 'pull_request'
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      e2e_apex_big_test: ${{ inputs.e2e_apex_big_test || 'false' }}
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test_push:
    name: E2E ApexBridge Tests (push on main/develop branch)
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    with:
      apex_bridge_ref: main
      e2e_apex_big_test: false
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
